sudo: required
language: generic

services:
  - docker

-before_install:
  - docker build -t jerekshoe/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true jerekshoe/docker-react npm run test